# Generated by Django 3.1 on 2020-08-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Наименование')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('capacity', models.IntegerField(verbose_name='Количество мест')),
                ('lesson_type', models.IntegerField(choices=[(0, 'практические'), (1, 'теоретические'), (2, 'практические/теоретические')], verbose_name='Вид занятий')),
            ],
            options={
                'verbose_name': 'Аудитория',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
            ],
            options={
                'verbose_name': 'Учебная программа',
            },
        ),
        migrations.CreateModel(
            name='CourseTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, verbose_name='Номер темы в курсе')),
                ('hours', models.IntegerField(verbose_name='Количество часов')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', unique=True, verbose_name='Учебная программа')),
            ],
            options={
                'verbose_name': 'Тема курса',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField(verbose_name='Начало лекции')),
                ('end', models.TimeField(verbose_name='Конец лекции')),
            ],
            options={
                'verbose_name': 'Шаблон дня',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('students_type', models.BooleanField(choices=[(False, 'Неавиационный персонал'), (True, 'Авиационный персонал')], verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Дисциплина',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тема',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Корпоративный аккаунт')),
                ('additional_email', models.EmailField(max_length=254, null=True, verbose_name='Дополнительный e-mail')),
                ('priority', models.IntegerField(choices=[(0, 'Если нет других свободных преподавателей'), (1, 'Минимальный'), (2, 'Средний'), (3, 'Максимальный')], verbose_name='Приоритет при распределении')),
                ('schedule', models.JSONField(default='{"type":0,"args":[5]}', verbose_name='График работы')),
                ('themes', models.ManyToManyField(to='main.Theme', verbose_name='Может проводить занятия по темам')),
            ],
            options={
                'verbose_name': 'Преподаватель',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('classrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.classroom', verbose_name='Аудитория')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Преподаватель')),
                ('themes', models.ManyToManyField(to='main.CourseTheme', verbose_name='Темы лекции')),
                ('time_interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scheduletemplate', verbose_name='Время проведения лекции')),
            ],
            options={
                'verbose_name': 'Лекция',
            },
        ),
        migrations.AddField(
            model_name='coursetheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.theme', unique=True, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Дисциплина'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='possible_courses',
            field=models.ManyToManyField(to='main.Course', verbose_name='Подходит для программ'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='top_priority_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Преимущество у дисциплины'),
        ),
    ]
