# Generated by Django 3.1 on 2020-08-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200815_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='possible_courses',
        ),
        migrations.AddField(
            model_name='classroom',
            name='possible_subjects',
            field=models.ManyToManyField(to='main.Subject', verbose_name='Подходит для дисциплин'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='top_priority_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_subj', to='main.subject', verbose_name='Преимущество у дисциплины'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Наименование'),
        ),
    ]
