# Generated by Django 3.1 on 2020-08-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200815_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='top_priority_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_subj', to='main.subject', verbose_name='Преимущество у дисциплины'),
        ),
        migrations.AlterField(
            model_name='coursetheme',
            name='theme_type',
            field=models.IntegerField(choices=[(0, 'практическая'), (1, 'теоретическая'), (2, 'оба типа')], verbose_name='Тип темы'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Дополнительный e-mail'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='schedule_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сколько дней может работать (оставить пустым для сменного графика)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='shifts',
            field=models.BinaryField(blank=True, max_length=4, null=True, verbose_name='Смены'),
        ),
    ]
