# Generated by Django 3.1 on 2020-08-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200816_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetheme',
            options={'verbose_name': 'Тема курса', 'verbose_name_plural': 'Темы курсов'},
        ),
        migrations.AlterField(
            model_name='coursetheme',
            name='number',
            field=models.CharField(max_length=5, null=True, verbose_name='Номер темы в курсе'),
        ),
    ]
